title: Melbi Language

description: >-
  Melbi is a flexible, expression-focused, and type-safe **embedded language**
  that allows power users and systems to define dynamic behavior and automation
  rules safely. It\'s built for speed and effortless sandboxing.

logo: "/assets/img/melbi-logo.svg"
favicon: "/assets/img/melbi-logo.svg"

aux_links:
  - [
      "<i data-lucide='github' class='icon'></i>",
      "https://github.com/melbi-lang/melbi",
    ]
  - [
      "<i data-lucide='sun' class='icon light-hidden'></i>
      <i data-lucide='moon' class='icon dark-hidden'></i>",
      "javascript:toggleTheme()",
    ]

domain: "melbi.dev"
url: "https://melbi.dev"
baseurl: ""
github_username: melbi-lang

#sass:
#  style: compressed

# color_scheme: light  # ignored: set in _includes/head.html
color_scheme: melbi
markdown: kramdown
theme: just-the-docs
plugins:
  - jekyll-feed
  - jekyll-sitemap
