title: Melbi Language

description: >-
  Melbi is a flexible, expression-focused, and type-safe **embedded language**
  that allows power users and systems to define dynamic behavior and automation
  rules safely. It\'s built for speed and effortless sandboxing.

aux_links:
  - [
      "<i data-lucide='github' class='w-5 h-5'></i>",
      "https://github.com/melbi-lang/melbi",
    ]
  # - [
  #     "<i data-lucide='sun' class='w-5 h-5 hidden dark:block'></i>
  #     <i data-lucide='moon' class='w-5 h-5 block dark:hidden'></i>",
  #     "javascript:void(0)",
  #   ]

domain: "melbi.dev"
url: "https://melbi.dev"
baseurl: ""
github_username: melbi-lang

color_scheme: light
markdown: kramdown
theme: just-the-docs
plugins:
  - jekyll-feed
  - jekyll-sitemap
